
// Authentication constants
export const CHAT_USER_REQUEST = 'CHAT_USER_REQUEST';
export const CHAT_USER_LOGIN_REQUEST = 'CHAT_USER_LOGIN_REQUEST';
export const CHAT_USER_LOGIN_SUCCESS = 'CHAT_USER_LOGIN_SUCCESS';
export const CHAT_USER_LOGIN_FAILURE = 'CHAT_USER_LOGIN_FAILURE';
export const CHAT_USER_LOGOUT = 'CHAT_USER_LOGOUT';

// Registration constants
export const CHAT_USER_REGISTER_REQUEST = 'CHAT_USER_REGISTER_REQUEST';
export const CHAT_USER_REGISTER_SUCCESS = 'CHAT_USER_REGISTER_SUCCESS';
export const CHAT_USER_REGISTER_FAILURE = 'CHAT_USER_REGISTER_FAILURE';
export const CHAT_USER_REGISTER_CANCEL = 'CHAT_USER_REGISTER_CANCEL';

// User constants
export const SET_USER_REQUEST = 'SET_USER_REQUEST';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_FAILURE = 'SET_USER_FAILURE';

export const CHAT_USERS_REQUEST = 'CHAT_USERS_REQUEST';
export const CHAT_USERS_SUCCESS = 'CHAT_USERS_SUCCESS';
export const CHAT_USERS_FAILURE = 'CHAT_USERS_FAILURE';
export const CHAT_USERS_RESET   = 'CHAT_USERS_RESET';

export const CHAT_CHANNEL_USERS_REQUEST = 'CHAT_CHANNEL_USERS_REQUEST';
export const CHAT_CHANNEL_USERS_SUCCESS = 'CHAT_CHANNEL_USERS_SUCCESS';
export const CHAT_CHANNEL_USERS_FAILURE = 'CHAT_CHANNEL_USERS_FAILURE';
export const CHAT_CHANNEL_USERS_RESET   = 'CHAT_CHANNEL_USERS_RESET';


export const CHAT_CHANNEL_REQUEST = 'CHAT_CHANNEL_REQUEST';
export const CHAT_CHANNEL_SUCCESS = 'CHAT_CHANNEL_SUCCESS';
export const CHAT_CHANNEL_FAILURE = 'CHAT_CHANNEL_FAILURE';

export const CHAT_MESSAGES_LIST_REQUEST = 'CHAT_MESSAGES_LIST_REQUEST';
export const CHAT_MESSAGES_LIST_UPDATE = 'CHAT_MESSAGES_LIST_UPDATE';
export const CHAT_WEBSOCKETS_CREATE_REQUEST = 'CHAT_WEBSOCKETS_CREATE_REQUEST';
export const CHAT_WEBSOCKETS_FETCH_REQUEST = 'CHAT_WEBSOCKETS_FETCH_REQUEST';
export const CHAT_MESSAGE_HISTORY_FAILURE_REQUEST = 'CHAT_MESSAGE_HISTORY_FAILURE_REQUEST';
